[workspace]
resolver = "2"
members = [
  "crates/vitte-core",
  "crates/vitte-vm",
  "crates/vitte-runtime",
  "crates/vitte-compiler",
  "crates/vitte-cli",
  "crates/vitte-tools",
  "crates/vitte-stdlib",
]
