# clippy.toml — règles de bon goût (et de survie) pour tout le repo

# Version minimale supportée (aligne avec ta CI / rust-toolchain.toml)
msrv = "1.80.0"

# ——— Complexité & lisibilité ———
# Baisse un peu les seuils pour attraper la dette avant qu’elle grossisse.
cognitive-complexity-threshold = 20      # défaut ≈ 25
too-many-arguments-threshold   = 6       # défaut 7
type-complexity-threshold      = 200     # défaut ≈ 250
too-many-lines-threshold       = 200     # pour clippy::too_many_lines
enum-variant-name-threshold    = 3       # préfixes d’enum trop verbeux
large-enum-variant-threshold   = 160     # bytes avant warning sur variants trop lourds

# ——— Docs ———
# Mots techniques acceptés par clippy::doc_markdown (pas de backticks requis)
doc-valid-idents = [
  "API", "ASCII", "CPU", "GPU", "TLS", "SSL", "HTTP", "HTTPS",
  "IPv4", "IPv6", "TCP", "UDP", "URL", "URI", "UUID", "ID",
  "NaN", "Inf", "UTF-8", "UTF-16", "JSON", "XML", "HTML",
  "WASM", "SIMD", "I/O", "CLI", "GUI", "FFI", "ABI",
  "ARM", "Cortex-M", "x86_64", "VTOR", "DMA", "ISR", "IRQ",
  "VGA", "PIT", "PIC", "GDT", "IDT",
]

# ——— Noms à bannir (par pitié) ———
# clippy::disallowed_names
disallowed-names = [
  "foo", "bar", "baz", "qux", "quux",
  "tmp", "temp", "data", "value", "var",
]

# ——— Interdits ciblés (types / méthodes / macros) ———
# Ces blocs nourrissent les lints:
#   - clippy::disallowed_types
#   - clippy::disallowed_methods
#   - clippy::disallowed_macros
# Ajuste selon ta stack (openssl → rustls, etc.).

[[disallowed-types]]
path = "std::sync::Mutex"
reason = "Préférer parking_lot::Mutex (perfs/poison)."

[[disallowed-types]]
path = "std::sync::RwLock"
reason = "Souvent sur-utilisé; parking_lot::RwLock ou mieux : revoir l’archi."

[[disallowed-methods]]
path = "std::mem::uninitialized"
reason = "UB land — utiliser MaybeUninit."

[[disallowed-methods]]
path = "std::process::Command::output"
reason = "Préférer un wrapper (timeouts, logs, erreurs enrichies)."

[[disallowed-macros]]
path = "dbg!"
reason = "OK en dev/test, pas en prod."

# ——— Tests : soyons pragmatiques ———
# Autoriser quelques raccourcis dans les tests uniquement.
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests    = true
allow-print-in-tests  = true
