[package]
name = "hello"
version = "0.1.0"
edition = "2025"
authors = ["Vincent <vincent@example.com>"]
license = "MIT OR Apache-2.0"
description = "Un projet Vitte minimal affichant Hello World"
repository = "https://github.com/lang-vitte/vitte"

[dependencies]
# stdlib incluse par défaut, pas besoin d'ajouter

[build]
# Commande de build personnalisée si besoin
# build-command = "make"

[profile.release]
opt-level = 3
lto = true
strip = true
