name: perf-budgets
on: [push, pull_request]
jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "vittest shard+ vitcov + vitcmp budgets (placeholder)"
